#!/bin/bash

decode_base64() {
  echo "$1" | base64 --decode
}

color_text() {
  local color_code="$1"
  local text="$2"
  echo -e "\033[${color_code}m${text}\033[0m"
}

print_help() {
  color_text "1;34" "Usage:"
  echo "  $(color_text "1;32" "$0 < kubernetes_secret.yaml")"
  echo "  $(color_text "1;32" "kubectl get secrets app-secret -o yaml | $0")"
  echo
  color_text "1;34" "Description:"
  echo "  $(color_text "0;37" "This script extracts and decodes Kubernetes secrets from a YAML file.")"
  echo "  $(color_text "0;37" "The YAML content should be piped into the script.")"
}

main() {
  in_data_section=false
  while IFS= read -r line; do
    if [[ "$line" =~ ^data: ]]; then
      in_data_section=true
      continue
    fi

    if [[ "$in_data_section" == true && "$line" =~ ^[a-zA-Z] ]]; then
      break
    fi

    if [[ "$in_data_section" == true && "$line" =~ ^[[:space:]]*([^:]+):[[:space:]]*(.+)$ ]]; then
      key="${BASH_REMATCH[1]}"
      value="${BASH_REMATCH[2]}"
      decoded_value=$(decode_base64 "$value")
      echo "export $key='$decoded_value'"
    fi
  done
}

if [ -t 0 ]; then
  print_help
else
  main
fi
