- name: "Install pip packages"
  pip:
    name: "{{ item }}"
  with_items:
    - pipenv    # creates and manages a virtualenv for your projects.
    - salt-lint # checks Salt State files (SLS) for best practices and behavior that could potentially be improved.
