- name: Install zsh
  apt:
    state: present
    name:
      - zsh

- name: Install Oh My Zsh
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/install_zsh.sh

- name: Run Oh My Zsh install script
  ansible.builtin.shell:
    cmd: ls ~/.oh-my-zsh || cat /tmp/install_zsh.sh | sh -s -- -y

- name: zsh-syntax-highlighting (Fish shell-like syntax highlighting for Zsh.)
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    update: yes

- name: zsh-autosuggestions (Fish-like fast/unobtrusive autosuggestions for zsh.)
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    update: yes

- name: zsh-kubectl-prompt (displays information about the kubectl current context and namespace in zsh prompt.)
  ansible.builtin.git:
    repo: 'https://github.com/superbrothers/zsh-kubectl-prompt.git'
    dest: ~/.oh-my-zsh/custom/plugins/zsh-kubectl-prompt
    update: yes

- name: Powerlevel10k Theme 
  ansible.builtin.git: 
    repo: 'https://github.com/romkatv/powerlevel10k.git'
    dest: ~/.oh-my-zsh/custom/themes/powerlevel10k
    update: yes
