- name: download Docker Installer
  ansible.builtin.get_url:
    url: https://get.docker.com
    dest: /tmp/docker.sh

- name: Run Docker install script
  ansible.builtin.shell:
    cmd: ls /etc/docker || cat /tmp/docker.sh | sh -s -- -y
  become: yes

- name: Reload Docker Service
  ansible.builtin.service:
    name: docker
    state: reloaded
  become: yes

- name: Install utility packages
  apt:
    state: present
    name:
      - zsh
      - net-tools
      - tree
      - jq
      - htop
      - dstat
      - curl
      - unattended-upgrades
      - neofetch
      - dnsutils
      - git
      - sysstat
      - iotop
      - python3-pip
      - nfs-common
      - libxrender1
      - nextcloud-desktop
      - google-chrome-stable
      - mongodb-compass
      - firefox
      - firefox-locale-en
      - firefox-locale-de
  become: yes

- name: Install AWS CLI
  pip:
    name: awscli

- name: Install skaffold
  ansible.builtin.get_url:
    url: https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
    dest: /usr/local/bin/skaffold
  become: yes

- name: make skaffold executable
  ansible.builtin.file:
    path: /usr/local/bin/skaffold
    owner: root
    group: root
    mode: '0755'
  become: yes

- name: Install kubectl
  ansible.builtin.get_url:
    url: https://dl.k8s.io/release/v1.22.0/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
  become: yes

- name: make kubectl executable
  ansible.builtin.file:
    path: /usr/local/bin/kubectl
    owner: root
    group: root
    mode: '0755'
  become: yes

- name: Install nvm (Node Version Manager)
  ansible.builtin.shell:
    cmd: ls ~/.nvm || curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash 

- name: Install Slack
  snap:
    name: slack
    classic: yes
  become: yes
