- name: download Docker Installer
  ansible.builtin.get_url:
    url: https://get.docker.com
    dest: /tmp/docker.sh

- name: Run Docker install script
  ansible.builtin.shell:
    cmd: ls /etc/docker || cat /tmp/docker.sh | sh -s -- -y
  become: True

- name: Reload Docker Service
  ansible.builtin.service:
    name: docker
    state: reloaded
  become: True

- name: Install utility packages
  apt:
    state: present
    name:
      - aspell            # interactive spell checker  
      - aspell-de 
      - aspell-en
      - bat               # A cat clone with syntax highlighting and Git integration.
      - btop              # Modern and colorful command line resource monitor that shows usage and stats
      - build-essential 
      - cmake 
      - cmatrix           # The Matrix
      - curl              # curl is a tool to transfer data from or to a server, using one of the supported protocols.
      - dnsutils          # is a flexible tool for interrogating DNS name servers. 
      - dstat             # versatile tool for generating system resource statistics
      - fd-find           # Simple, fast and user-friendly alternative to find
      - firefox           # browser
      - firefox-locale-de
      - gnupg             # GNU Privacy Guard
      - htop              # interactively monitor the system’s vital resources.
      - iotop             # iotop watches I/O usage information output by the Linux kernel  
      - jq                # jq is a lightweight and flexible command-line JSON processor.
      - lolcat            # color output
      - moc               # ncurses based console audio player
      - neofetch          # Shows Linux System Information with Distribution Logo
      - net-tools         # collection of base networking utilities for Linux.
      - nextcloud-desktop # Connect to your Nextcloud from Windows, macOS or Linux.
      - nfs-common        # nsf tools
      - nmap              # network scanner
      - nodejs            # V8 javascript runtime 
      - pwgen             # Automatic Password generation
      - python-setuptools # 
      - python3-dev       # 
      - python3-pip       # package installer for Python.
      - python3.10-venv   # install python3 virtualenv
      - rdesktop          # RDP client for Windows Terminal Server 
      - ripgrep           # ripgrep is a line-oriented search tool that recursively searches the current directory for a regex pattern.
      - shellcheck        # lint tool for shell scripts
      - silversearcher-ag # A code searching tool 
      - snapd             #   
      - software-properties-common
      - sqlite3           # sqlite3 client 
      - sysstat           # system performance tools for Linux
      - terminator        # terminal
      - tig               # ncurses-based text-mode interface for Git
      - tree              # recursively list or display the content of a directory in a tree-like format.
      - zsh               # nice shell
  become: True

- name: Install checkssl
  ansible.builtin.get_url:
    url: https://github.com/szazeski/checkssl/releases/download/v0.4.3/checkssl_0.4.3_Linux_x86_64.tar.gz
    dest: /usr/bin/checkssl
    force: no
  become: True

- name: make checkssl executable
  ansible.builtin.file:
    path: /usr/bin/checkssl
    owner: root
    group: root
    mode: '0755'
  become: True

- name: Install AWS CLI
  pip:
    name: awscli

- name: Install ppa:neovim
  ansible.builtin.shell:
    cmd: add-apt-repository ppa:neovim-ppa/unstable
  become: True

- name: Install neovim
  apt:
    state: present
    name: neovim
    update_cache: True
  become: True

- name: add google ppa
  ansible.builtin.shell:
    cmd: wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add - 

- name: add google source list
  ansible.builtin.shell:
    cmd: echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | sudo tee /etc/apt/sources.list.d/google-chrome.list

- name: Install google-chrome-stable
  apt:
    state: present
    name: google-chrome-stable
    update_cache: True
  become: True

- name: Install skaffold
  ansible.builtin.get_url:
    url: https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
    dest: /usr/local/bin/skaffold
    force: no
  become: True

- name: make skaffold executable
  ansible.builtin.file:
    path: /usr/local/bin/skaffold
    owner: root
    group: root
    mode: '0755'
  become: True

- name: Install kubens
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/ahmetb/kubectx/master/kubens
    dest: /usr/local/bin/kubens
    force: no
  become: True

- name: make kubens executable
  ansible.builtin.file:
    path: /usr/local/bin/kubens
    owner: root
    group: root
    mode: '0755'
  become: True

- name: Install kubeval
  ansible.builtin.get_url:
    url: https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz
    dest: /tmp/kubeval-linux-amd64.tar.gz
    force: no

- name: Extract /tmp/kubeval-linux-amd64.tar.gz
  ansible.builtin.unarchive:
    src: /tmp/kubeval-linux-amd64.tar.gz
    dest: /tmp

- name: Copy kubeval binary
  ansible.builtin.copy:
    src: /tmp/kubeval
    dest: /usr/local/bin/kubeval
    mode: '0555'
  become: True

- name: Install Minikube
  ansible.builtin.get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /usr/local/bin/minikube
    force: no
  become: True

- name: make Minikube executable
  ansible.builtin.file:
    path: /usr/local/bin/minikube
    owner: root
    group: root
    mode: '0755'
  become: True

- name: Install kubectl
  ansible.builtin.get_url:
    url: https://dl.k8s.io/release/v1.26.2/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    force: no
  become: True

- name: make kubectl executable
  ansible.builtin.file:
    path: /usr/local/bin/kubectl
    owner: root
    group: root
    mode: '0755'
  become: True

- name: Install lazygit
  ansible.builtin.get_url:
    url: https://github.com/jesseduffield/lazygit/releases/download/v0.37.0/lazygit_0.37.0_Linux_x86_64.tar.gz
    dest: /tmp/lazygit.tar.gz
    force: no

- name: Extract /tmp/lazygit.tar.gz
  ansible.builtin.unarchive:
    src: /tmp/lazygit.tar.gz
    dest: /usr/local/bin/
  become: True

- name: make lazygit executable
  ansible.builtin.file:
    path: /usr/local/bin/lazygit
    owner: root
    group: root
    mode: '0755'
  become: True

- name: Install lazydocker
  ansible.builtin.shell:
    cmd: curl https://raw.githubusercontent.com/jesseduffield/lazydocker/master/scripts/install_update_linux.sh | bash

- name: download k9s
  ansible.builtin.get_url:
    url: https://github.com/derailed/k9s/releases/download/v0.27.4/k9s_Linux_amd64.tar.gz
    dest: /tmp/k9s_Linux_amd64.tar.gz
    force: no

- name: Extract /tmp/k9s_Linux_amd64.tar.gz
  ansible.builtin.unarchive:
    src: /tmp/k9s_Linux_amd64.tar.gz
    dest: /tmp

- name: Copy k9s binary
  ansible.builtin.copy:
    src: /tmp/k9s
    dest: /usr/local/bin/k9s
    mode: '0555'
  become: True

- name: Install helm 3
  ansible.builtin.shell:
    cmd: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash 

- name: download velero
  ansible.builtin.get_url:
    url: https://github.com/vmware-tanzu/velero/releases/download/v1.7.1/velero-v1.7.1-linux-amd64.tar.gz
    dest: /tmp/velero-v1.7.1-linux-amd64.tar.gz
    force: no

- name: Extract /tmp/velero-v1.7.1-linux-amd64.tar.gz
  ansible.builtin.unarchive:
    src: /tmp/velero-v1.7.1-linux-amd64.tar.gz
    dest: /tmp

- name: Copy velero binary
  ansible.builtin.copy:
    src: /tmp/velero-v1.7.1-linux-amd64/velero
    dest: /usr/local/bin/velero
    mode: '0555'
  become: True

- name: download golang (don't installed new version of Go on top a previous one. rm -rvf /usr/local/go/)
  ansible.builtin.get_url:
    url: https://go.dev/dl/go1.17.6.linux-amd64.tar.gz
    dest: /usr/local/go1.17.6.linux-amd64.tar.gz
    force: no
  become: True

- name: Extract go1.17.6.linux-amd64.tar.gz
  ansible.builtin.unarchive:
    src: /usr/local/go1.17.6.linux-amd64.tar.gz
    dest: /usr/local
  become: True

- name: download protoc (API for protocol buffers using modern Haskell language and library patterns.)
  ansible.builtin.get_url:
    url: https://github.com/protocolbuffers/protobuf/releases/download/v3.14.0/protoc-3.14.0-linux-x86_64.zip
    dest: /usr/local/protoc-3.14.0-linux-x86_64.zip
    force: no
  become: True

- name: Extract protoc-3.14.0-linux-x86_64.zip
  ansible.builtin.unarchive:
    src: /usr/local/protoc-3.14.0-linux-x86_64.zip
    dest: /usr/local
  become: True
  
- name: get and install argocd cli 
  ansible.builtin.get_url:
    url: https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
    dest: /usr/local/bin/argocd
    mode: '0555'
    force: no
  become: True

- name: get argo cli 
  ansible.builtin.get_url:
    url: https://github.com/argoproj/argo-workflows/releases/download/v3.2.6/argo-linux-amd64.gz
    dest: /tmp
    force: no

- name: Extract argo-linux-amd64.gz
  ansible.builtin.shell:
    cmd: ls /tmp/argo-linux-amd64 || gunzip argo-linux-amd64.gz
    chdir: /tmp

- name: Copy argo cli binary
  ansible.builtin.copy:
    src: /tmp/argo-linux-amd64
    dest: /usr/local/bin/argo
    mode: '0555'
  become: True

- name: Install nvm (Node Version Manager)
  ansible.builtin.shell:
    cmd: ls ~/.nvm || curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash 

- name: Setup nvm env
  ansible.builtin.shell:
    cmd: cat /home/tino/.nvm/nvm.sh | bash  # This loads nvm 
  become: True

- name: Install Slack chat client
  snap:
    name: slack
    classic: True
  become: True

- name: download fzf command-line fuzzy finder
  ansible.builtin.git:
    repo: 'https://github.com/junegunn/fzf.git'
    dest: ~/.fzf
    update: True

- name: install fzf
  ansible.builtin.shell:
    cmd: ~/.fzf/install
#  become: True
#
- name: install z
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/rupa/z/master/z.sh
    dest: /usr/local/bin/z.sh
    mode: '777'
  become: True

- name: install todo.sh
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/todotxt/todo.txt-cli/master/todo.sh
    dest: /usr/local/bin/todo.sh
    mode: '777'
  become: True

- name: move youtube downloader in place
  copy:
    src: files/ydl.sh
    dest: /usr/local/bin/ydl.sh
    mode: '774'
  become: True
  
- name: create .toto folder
  file:
    path: ~/.todo
    state: directory

- name: get .todo-config
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/tinoschroeter/dotfiles/master/todo-config
    dest: ~/.todo/config

- name: copy cht.sh to /usr/local/bin/
  ansible.builtin.copy:
    src: cht.sh
    dest: /usr/local/bin/cht.sh
    mode: '777'
  become: True

- name: copy spell.sh to /usr/local/bin/
  ansible.builtin.copy:
    src: spell.sh
    dest: /usr/local/bin/spell.sh
    mode: '777'
  become: True

- name: copy sync-zsh-history to /usr/local/bin/
  ansible.builtin.copy:
    src: sync-zsh-history/index.js
    dest: /usr/local/bin/sync-zsh-history.js
    mode: '777'
  become: True
