- name: download Docker Installer
  ansible.builtin.get_url:
    url: https://get.docker.com
    dest: /tmp/docker.sh

- name: Run Docker install script
  ansible.builtin.shell:
    cmd: ls /etc/docker || cat /tmp/docker.sh | sh -s -- -y
  become: yes

- name: Reload Docker Service
  ansible.builtin.service:
    name: docker
    state: reloaded
  become: yes

- name: Install utility packages
  apt:
    state: present
    name:
      - terminator # terminal
      - zsh        # nice shell
      - gnupg      # GNU Privacy Guard
      - net-tools  # collection of base networking utilities for Linux.
      - nmap       # network scanner
      - tree       # recursively list or display the content of a directory in a tree-like format.
      - jq         # jq is a lightweight and flexible command-line JSON processor.
      - htop       # interactively monitor the system’s vital resources.
      - dstat      # versatile tool for generating system resource statistics
      - curl       # curl is a tool to transfer data from or to a server, using one of the supported protocols.
      - neofetch   #
      - dnsutils   # is a flexible tool for interrogating DNS name servers. 
      - git        # fast, scalable, distributed revision control system
      - sysstat    #
      - iotop      # iotop watches I/O usage information output by the Linux kernel  
      - python3-pip       # package installer for Python.
      - python-setuptools # 
      - nfs-common        # nsf tools
      - snapd             #   
      - nextcloud-desktop    # Connect to your Nextcloud from Windows, macOS or Linux.
      - firefox              # browser
      - firefox-locale-en
      - firefox-locale-de
      - aspell            # interactive spell checker  
      - aspell-de 
      - aspell-en
      - lolcat           # color output
  become: yes

- name: Install AWS CLI
  pip:
    name: awscli

- name: add google ppa
  ansible.builtin.shell:
    cmd: wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add - 

- name: add google source list
  ansible.builtin.shell:
    cmd: sudo sh -c 'echo "deb https://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/google.list'

- name: Install google-chrome-stable
  apt:
    state: present
    name: google-chrome-stable
    update_cache: yes
  become: yes

- name: Install skaffold
  ansible.builtin.get_url:
    url: https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
    dest: /usr/local/bin/skaffold
  become: yes

- name: make skaffold executable
  ansible.builtin.file:
    path: /usr/local/bin/skaffold
    owner: root
    group: root
    mode: '0755'
  become: yes

- name: Install Minikube
  ansible.builtin.get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /usr/local/bin/minikube
  become: yes

- name: make Minikube executable
  ansible.builtin.file:
    path: /usr/local/bin/minikube
    owner: root
    group: root
    mode: '0755'
  become: yes

- name: Install kubectl
  ansible.builtin.get_url:
    url: https://dl.k8s.io/release/v1.22.0/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
  become: yes

- name: make kubectl executable
  ansible.builtin.file:
    path: /usr/local/bin/kubectl
    owner: root
    group: root
    mode: '0755'
  become: yes

#- name: Add the HashiCorp GPG key
#  ansible.builtin.shell:
#    cmd: 
#      - curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
#      - sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"

- name: install the Terraform CLI.
  apt:
    name: terraform
    update_cache: yes
  become: yes

- name: Install helm 3
  ansible.builtin.shell:
    cmd: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash 

- name: download velero
  ansible.builtin.get_url:
    url: https://github.com/vmware-tanzu/velero/releases/download/v1.7.1/velero-v1.7.1-linux-amd64.tar.gz
    dest: /tmp/velero-v1.7.1-linux-amd64.tar.gz

- name: Extract /tmp/velero-v1.7.1-linux-amd64.tar.gz
  ansible.builtin.unarchive:
    src: /tmp/velero-v1.7.1-linux-amd64.tar.gz
    dest: /tmp

- name: Copy velero binary
  ansible.builtin.copy:
    src: /tmp/velero-v1.7.1-linux-amd64/velero
    dest: /usr/local/bin/velero
    mode: '0555'
  become: yes

- name: Install nvm (Node Version Manager)
  ansible.builtin.shell:
    cmd: ls ~/.nvm || curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash 

#- name: Setup nvm env
#  ansible.builtin.shell:
#    cmd: /home/tino/.nvm/nvm.sh  # This loads nvm 
#  become: yes

#- name: Install Node 16
#  ansible.builtin.shell:
#    cmd: nvm install 16

- name: Install Slack chat client
  snap:
    name: slack
    classic: yes
  become: yes
