- name: get .zshrc
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/tinoschroeter/dotfiles/master/.zshrc
    dest: ~/.zshrc

- name: get .vimrc
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/tinoschroeter/dotfiles/master/.vimrc
    dest: ~/.vimrc

- name: get .banner
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/tinoschroeter/dotfiles/master/.banner
    dest: ~/.banner

- name: get .gitconfig
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/tinoschroeter/dotfiles/master/.gitconfig
    dest: ~/.gitconfig

- name: get .p10k.zsh
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/tinoschroeter/dotfiles/master/.p10k.zsh
    dest: ~/.p10k.zsh

- name: get dockerfile.vim
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/tinoschroeter/dotfiles/master/dockerfile.vim
    dest: ~/.vim/dockerfile.vim

- name: get coc-settings.json
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/tinoschroeter/dotfiles/master/coc-settings.json
    dest: ~/.vim/coc-settings.json

- name: create terminator config file 
  ansible.builtin.file:
    path: ~/.config/terminator
    state: directory

- name: Copy terminator config
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/tinoschroeter/dotfiles/master/.config/terminator/config 
    dest: ~/.config/terminator/config

# moc ncurses based console audio player
#
- name: Create a directory for moc if it does not exist
  ansible.builtin.file:
    path: ~/.moc
    state: directory
    mode: '0755'

- name: create moc config file
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/tinoschroeter/dotfiles/master/moc/config
    dest: ~/.moc/config

- name: create moc keymap file
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/tinoschroeter/dotfiles/master/moc/keymap
    dest: ~/.moc/keymap

- name: create .secrets file
  ansible.builtin.file:
    path: ~/.secrets
    state: touch
    mode: 400
