- name: get .zshrc
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/tinoschroeter/dotfiles/master/.zshrc
    dest: ~/.zshrc

- name: get .vimrc
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/tinoschroeter/dotfiles/master/.vimrc
    dest: ~/.vimrc

- name: get .banner
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/tinoschroeter/dotfiles/master/.banner
    dest: ~/.banner

- name: get .gitconfig
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/tinoschroeter/dotfiles/master/.gitconfig
    dest: ~/.gitconfig

- name: get .p10k.zsh
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/tinoschroeter/dotfiles/master/.p10k.zsh
    dest: ~/.p10k.zsh

- name: get dockerfile.vim
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/tinoschroeter/dotfiles/master/dockerfile.vim
    dest: ~/.vim/dockerfile.vim

- name: create terminator config file 
  ansible.builtin.file:
    path: ~/.config/terminator
    state: directory

- name: Copy terminator config
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/tinoschroeter/dotfiles/master/.config/terminator/config 
    dest: ~/.config/terminator/config

- name: create .secrets file
  ansible.builtin.file:
    path: ~/.secrets
    state: touch
    mode: 400
