- name: get .zshrc
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/tinoschroeter/dotfiles/master/.zshrc
    dest: ~/.zshrc

- name: get .vimrc
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/tinoschroeter/dotfiles/master/.vimrc
    dest: ~/.vimrc

- name: Copy terminator config
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/tinoschroeter/dotfiles/master/.config/terminator/config 
    dest: ~/.config/terminator/config

- name: create .secrets file
  ansible.builtin.file:
    path: ~/.secrets
    state: touch
    mode: 400
