- name: Install vim
  apt:
    state: present
    name:
      - vim
  become: yes

- name: Creates autoload directory
  file:
    path: ~/.vim/autoload
    state: directory

- name: Creates bundle directory
  file:
    path: ~/.vim/bundle
    state: directory

- name: install pathogen 
  get_url:
    url: https://raw.githubusercontent.com/tpope/vim-pathogen/master/autoload/pathogen.vim
    dest: ~/.vim/autoload/pathogen.vim

- name: addon indentLine.vim (A light and configurable statusline/tabline plugin for Vim)
  ansible.builtin.git:
    repo: 'https://github.com/itchyny/lightline.vim.git'
    dest: ~/.vim/bundle/lightline.vim
    update: yes

- name: addon mundo.vim (A Vim plugin to visualizes the Vim undo tree.)
  ansible.builtin.git:
    repo: 'https://github.com/simnalamburt/vim-mundo.git'
    dest: ~/.vim/bundle/vim-mundo
    update: yes

- name: Create undo directory
  ansible.builtin.file:
    path: ~/.vim/undo
    state: directory

- name: addon nerdtree.vim (The NERDTree is a file system explorer for the Vim editor.)
  ansible.builtin.git:
    repo: 'https://github.com/scrooloose/nerdtree.git'
    dest: ~/.vim/bundle/nerdtree
    update: yes

- name: addon ultisnips.vim (UltiSnips is the ultimate solution for snippets in Vim.)
  ansible.builtin.git:
    repo: 'https://github.com/SirVer/ultisnips.git'
    dest: ~/.vim/bundle/ultisnips
    update: yes

- name: setup my ultisnips
  ansible.builtin.git:
    repo: 'https://github.com/tinoschroeter/vim.UltiSnips.git'
    dest: ~/.vim/UltiSnips
    update: yes

- name: addon vim-irblack.vim (Infinite Red's vim theme)
  ansible.builtin.git:
    repo: 'https://github.com/wgibbs/vim-irblack.git'
    dest: ~/.vim/bundle/vim-irblack
    update: yes

- name: addon vim-prettier.vim (An opinionated code formatter)
  ansible.builtin.git:
    repo: 'https://github.com/prettier/vim-prettier.git'
    dest: ~/.vim/bundle/vim-prettier

- name: addon vim-snippets.vim (This repository contains snippets files for various programming languages.)
  ansible.builtin.git:
    repo: 'https://github.com/honza/vim-snippets.git'
    dest: ~/.vim/bundle/vim-snippets
    update: yes

- name: Create symbolic link for vim_snippets
  ansible.builtin.file:
    src: ~/.vim/bundle/vim-snippets/autoload/vim_snippets.vim
    dest: ~/.vim/autoload/vim_snippets.vim
    state: link
