- name: Install vim
  apt:
    state: present
    name:
      - vim

- name: Create undo directory
  ansible.builtin.file:
    path: ~/.vim/undo
    state: directory

- name: My UltiSnips
  ansible.builtin.git:
    repo: 'https://github.com/tinoschroeter/vim.UltiSnips.git'
    dest: ~/.vim/UltiSnips
    update: yes

- name: add undo file 
  ansible.builtin.file:
    path: ~/.vim/undo

- name: addon indentLine.vim
  ansible.builtin.git:
    repo: 'https://github.com/itchyny/lightline.vim.git'
    dest: ~/.vim/bundle/lightline.vim
    update: yes

- name: addon mundo.vim
  ansible.builtin.git:
    repo: 'https://github.com/simnalamburt/vim-mundo.git'
    dest: ~/.vim/bundle/vim-mundo
    update: yes

- name: addon nerdtree.vim
  ansible.builtin.git:
    repo: 'https://github.com/scrooloose/nerdtree.git'
    dest: ~/.vim/bundle/nerdtree
    update: yes

- name: addon ultisnips.vim
  ansible.builtin.git:
    repo: 'https://github.com/SirVer/ultisnips.git'
    dest: ~/.vim/bundle/ultisnips
    update: yes

- name: addon vim-irblack.vim
  ansible.builtin.git:
    repo: 'https://github.com/wgibbs/vim-irblack.git'
    dest: ~/.vim/bundle/vim-irblack
    update: yes

- name: addon vim-prettier.vim
  ansible.builtin.git:
    repo: 'https://github.com/prettier/vim-prettier.git'
    dest: ~/.vim/bundle/vim-prettier
    update: yes

- name: addon vim-snippets.vim
  ansible.builtin.git:
    repo: 'https://github.com/honza/vim-snippets.git'
    dest: ~/.vim/bundle/vim-snippets
    update: yes
